common:
    exp_name: config_crf_glove_004
    arch: AspectSent
    batch_size: 16

    #Map words to lower case
    embed_num: 5120
    #For elmo the emb_size is 1024
    embed_dim: 300
    mask_dim: 30
    if_update_embed: True

    # lstm
    #l_hidden_size: 256
    l_hidden_size: 300
    l_num_layers: 2 # forward and backward
    l_dropout: 0.1

    # penlaty
    C1: 0.1
    C2: 0.00
    if_reset: True

    opt: Adam
    dropout: 0.5
    epoch: 30
    lr: 0.001
    l2: 0.000
    adjust_every: 8
    clip_norm: 3
    k_fold: 6
    print_freq: 20
    finetune_embed: False
    # data processing
    if_replace: False
    training: True
    # traning
    if_gpu: True
    use_gpu: True
    # data_path: data/2014/data.pkl
    # dic_path: data/2014/dic.pkl

    #################Restaurant
    pretrained_embed_path: ../data/glove.840B.300d.txt
    embed_path: data/restaurant_parse/vocab/local_emb.pkl
    data_path: data/restaurant_parse/
    train_path: data/restaurant_parse/train.pkl
    valid_path: data/restaurant_parse/valid.pkl
    test_path: data/restaurant_parse/Restaurants_Test_Gold.xml.pkl
    dic_path: data/restaurant_parse/vocab/dict.pkl


    model_path: data/models/
    log_path: data/logs/
    
    is_stanford_nlp: True
    elmo_config_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_options.json
    elmo_weight_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
    snapshot_dir: checkpoints/