common:
    exp_name: unsupervised_exp003
    arch: Tri_RNNCNNSent
    batch_size: 32

    #Map words to lower case
    embed_num: 5120
    #For elmo the emb_size is 1024
    embed_dim: 100
    mask_dim: 50
    if_update_embed: True

    # lstm
    #l_hidden_size: 256
    l_hidden_size: 256
    l_num_layers: 2 # forward and backward
    l_dropout: 0.1
    threshold: 0.6
    # penlaty
    C1: 0.1
    lambda_f: 1
    C2: 0.001
    if_reset: True

    opt: Adam
    dropout: 0.5
    epoch: 30
    lr: 0.0001
    l2: 0.001
    adjust_every: 8
    clip_norm: 3
    k_fold: 6
    print_freq: 10
    finetune_embed: False
    # data processing
    if_replace: False
    training: True
    # traning
    if_gpu: True
    use_gpu: True
    # data_path: data/2014/data.pkl
    # dic_path: data/2014/dic.pkl

    #################Restaurant
    pretrained_embed_path: ../data/glove.840B.300d.txt
    embed_path: data/indo/vocab/local_emb.pkl
    data_path: data/indo/
    source_path: data/indo/source.pkl
    target_train_path: data/indo/target_dev.pkl
    test_path: data/indo/target_dev.pkl
    dic_path: data/indo/vocab/dict.pkl


    model_path: data/models/
    log_path: data/logs/
    
    is_stanford_nlp: True
    elmo_config_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_options.json
    elmo_weight_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
    snapshot_dir: checkpoints/
