common:
    exp_name: crf_mem_indo_20181209
    arch: CRF_Mem_AspectSent
    batch_size: 32

    #Map words to lower case
    embed_num: 31411
    #For elmo the emb_size is 1024
    embed_dim: 100
    mask_dim: 30
    if_update_embed: False

    # lstm
    #l_hidden_size: 256
    l_hidden_size: 128
    l_num_layers: 2 # forward and backward
    l_dropout: 0.1

    # penlaty
    C1: 0.2
    C2: 0.04
    if_reset: False

    opt: Adam
    dropout: 0.5
    epoch: 30
    lr: 0.001
    l2: 0.0
    adjust_every: 8
    clip_norm: 3
    k_fold: 6
    print_freq: 10
    finetune_embed: False
    # data processing
    if_replace: False
    training: True
    # traning
    if_gpu: True
    use_gpu: True
    # data_path: data/2014/data.pkl
    # dic_path: data/2014/dic.pkl

    #################Restaurant
    pretrained_embed_path: ../data/glove.840B.300d.txt
    embed_path: data/indo/vocab/local_emb.pkl
    data_path: data/indo/
    train_path: data/indo/train.xml.pkl
    valid_path: data/indo/dev.xml.pkl
    test_path: data/indo/test.xml.pkl
    dic_path: data/indo/vocab/dict.pkl


    model_path: data/models/
    log_path: data/logs/
    
    is_stanford_nlp: False
    elmo_config_file: ../data/Indo_Elmo/options.json
    elmo_weight_file: ../data/Indo_Elmo/weights.hdf5
    snapshot_dir: checkpoints/