common:
    exp_name: config_dnm_laptop_20181218
    arch: DynamicMemTSA
    batch_size: 32

    #Map words to lower case
    embed_num: 4063
    #For elmo the emb_size is 1024
    embed_dim: 300
    mask_dim: 30
    if_update_embed: False

    # lstm
    #l_hidden_size: 256
    l_hidden_size: 256
    l_num_layers: 2 # forward and backward
    l_dropout: 0.1

    # penlaty
    C1: 0.2
    C2: 0.05
    if_reset: True

    opt: Adagrad
    dropout: 0.5
    epoch: 50
    lr: 0.003
    l2: 0.0001
    adjust_every: 8
    clip_norm: 3
    k_fold: 6
    print_freq: 50
    finetune_embed: False
    # data processing
    if_replace: False
    training: True
    # traning
    if_gpu: True
    use_gpu: True
    # data_path: data/2014/data.pkl
    # dic_path: data/2014/dic.pkl

    #################Restaurant
    pretrained_embed_path: ../data/glove.840B.300d.txt
    embed_path: data/laptop/vocab/local_emb.pkl
    data_path: data/laptop/
    train_path: data/laptop/train.pkl
    valid_path: data/laptop/valid.pkl
    test_path: data/laptop/Laptops_Test_Gold.xml.pkl
    dic_path: data/laptop/vocab/dict.pkl


    model_path: data/models/
    log_path: data/logs/
    
    is_stanford_nlp: False
    elmo_config_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_options.json
    elmo_weight_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
    snapshot_dir: checkpoints/