common:
    exp_name: config_crf_glove_indo_leiming
    arch: AspectSent
    batch_size: 32

    #Map words to lower case
    embed_num: 16795
    #For elmo the emb_size is 1024
    embed_dim: 100
    mask_dim: 30
    if_update_embed: False

    # lstm
    #l_hidden_size: 256
    l_hidden_size: 200
    l_num_layers: 4 # forward and backward
    l_dropout: 0.1

    # penlaty
    C1: 0.1
    C2: 0.001
    if_reset: True

    opt: Adam
    dropout: 0.5
    dropout2: 0.1
    epoch: 30
    lr: 0.001
    l2: 0.0
    adjust_every: 8
    clip_norm: 3
    k_fold: 6
    print_freq: 20
    finetune_embed: False
    # data processing
    if_replace: False
    training: True
    # traning
    if_gpu: True
    use_gpu: True
    # data_path: data/2014/data.pkl
    # dic_path: data/2014/dic.pkl

    #################Restaurant
    pretrained_embed_path: ../data/glove_indo.100d.txt
    embed_path: data/indo_leiming/vocab/local_emb.pkl
    data_path: data/indo_leiming/
    train_path: data/indo_leiming/train_data_original.csv.pkl
    valid_path: data/indo_leiming/dev_data_original.csv.pkl
    test_path: data/indo_leiming/test_data_original.csv.pkl
    dic_path: data/indo_leiming/vocab/dict.pkl


    model_path: data/models/
    log_path: data/logs/
    
    is_stanford_nlp: False
    elmo_config_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_options.json
    elmo_weight_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
    snapshot_dir: checkpoints/