common:
    exp_name: config_gcnn_elmo_tweets_20181230
    arch: ElmoGCNNTSA
    batch_size: 32

    #Map words to lower case
    embed_num: 15906
    #For elmo the emb_size is 1024
    embed_dim: 1024
    mask_dim: 30
    if_update_embed: False

    # lstm
    #l_hidden_size: 256
    l_hidden_size: 64
    l_num_layers: 2 # forward and backward
    l_dropout: 0.1

    # penlaty
    C1: 0.1
    C2: 0.02
    if_reset: True

    opt: Adagrad
    dropout: 0.5
    epoch: 30
    lr: 0.05
    l2: 0.008
    adjust_every: 8
    clip_norm: 3
    k_fold: 6
    print_freq: 20
    finetune_embed: False
    # data processing
    if_replace: False
    training: True
    # traning
    if_gpu: True
    use_gpu: True
    # data_path: data/2014/data.pkl
    # dic_path: data/2014/dic.pkl

    #################Restaurant
    pretrained_embed_path: ../data/glove.840B.300d.txt
    embed_path: data/tweets/vocab/local_emb.pkl
    data_path: data/tweets/
    train_path: data/tweets/train.pkl
    valid_path: data/tweets/valid.pkl
    test_path: data/tweets/test.csv.pkl
    dic_path: data/tweets/vocab/dict.pkl


    model_path: data/models/
    log_path: data/logs/
    
    is_stanford_nlp: True
    elmo_config_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_options.json
    elmo_weight_file: ../data/Elmo/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
    snapshot_dir: checkpoints/